[package]
name = "janus"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "janus"
path = "src/janus.rs"

[dependencies]
regex = "1.8.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
